name: Code Quality

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ '*' ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        uv venv --python 3.12
        uv pip install -e ".[dev]"
        uv pip install -e ".[test]"
        uv pip install pylint mypy types-requests

    - name: Run pylint
      run: |
        source .venv/bin/activate
        pylint --disable=all --enable=unused-import,unused-variable,unused-argument,redefined-outer-name src/ || true

    - name: Run mypy type checking
      run: |
        source .venv/bin/activate
        mypy --ignore-missing-imports src/ || true

